tr1:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory:
      RightPosition:
        type: effort_controllers/JointTrajectoryController
        joints:
          - JointRightShoulderPan
          - JointRightShoulderTilt        
        gains:
          JointRightShoulderPan: {p: 6.0, i: 0.0, d: 0.0, i_clamp: 1.0}
          JointRightShoulderTilt: {p: 15.0, i: 0.1, d: 1.0, i_clamp: 1.0}
        constraints:
          goal_time: 10.0
          JointRightShoulderPan:
            goal: 0.1
          JointRightShoulderTilt:
            goal: 0.1

    position:
      JointRightShoulderPan:
        type: effort_controllers/JointPositionController
        joint: JointRightShoulderPan
        pid: {p: 3.0, i: 0.3, d: 0.0, i_clamp: 1.0}
      JointRightShoulderTilt:
        type: effort_controllers/JointPositionController
        joint: JointRightShoulderTilt
        pid: {p: 15.0, i: 0.0, d: 1.0, i_clamp: 0.0}

    effort:
      JointRightShoulderPan:
        type: effort_controllers/JointEffortController
        joint: JointRightShoulderPan
      JointRightShoulderTilt:
        type: effort_controllers/JointEffortController
        joint: JointRightShoulderTilt

