tr1:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 150
    trajectory:
      RightPosition:
        type: effort_controllers/JointTrajectoryController
        joints:
          - JointRightShoulderPan
        gains:
          JointRightShoulderPan: {p: 8.5, i: 0.3, d: 0.1, i_clamp: 1.0}
        constraints:
          goal_time: 10.0
          JointRightShoulderPan:
            goal: 0.1
    position:
      JointRightShoulderPan:
        type: effort_controllers/JointPositionController
        joint: JointRightShoulderPan
        pid: {p: 8.5, i: 0.3, d: 0.1, i_clamp: 1.0}

    effort:

      JointRightShoulderPan:
        type: effort_controllers/JointEffortController
        joint: JointRightShoulderPan
